# Job to download all dependencies and save as artifacts for subsequent jobs.
# Job only runs if a go.sum file exists. For details see
# https://go.dev/ref/mod#go-mod-download.

include:
  - local: '/ci/templates/Go-Template.gitlab-ci.yml'

go-mod-download:
  extends:
    - .go
  stage: .pre
  needs: []
  rules:
    - exists:
        - '**/go.sum'
  before_script:
    ## Required since this is set as GOPATH
    - mkdir -p .go
  script:
    - go mod download
  artifacts:
    paths:
      - .go/pkg/mod/
  cache:
    key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/go-build
      - .go/pkg/mod/
    policy: pull-push
